"""Phase-2 per-cell LoRA training: one adapter per (environment, era) cell.

adapterCL.md 7 Phase 2 asks for "one LoRA per (environment, era) cell -- 18
cells", which the 6.2 transfer matrix then cross-applies. This module produces
the LLaMA-Factory jobs that do it: one generated YAML per cell, the exact shell
commands to run them, a cost table for the Phase-1 sweep, and a collector that
validates what came back.

It follows `self-correct/sft_cell.sh`'s pattern -- LLaMA-Factory here is
YAML-only (it rejects CLI overrides), so every run needs its own file -- but does
the generation in python instead of `sed`, because a LoRA recipe changes more
fields than a sed chain can safely carry, and because `lora_target` has to come
from `targets.peft_target_modules()` rather than from `all` (4.5: `all` is unsafe
on this hybrid architecture -- it would match the vision tower and `conv1d`,
which vLLM silently drops at serve time).

Three deliberate differences from `sft_cell.sh`:

* **Generated YAMLs live in `out/cells/<tag>/yaml/`, not in the LLaMA-Factory
  tree.** `lmf train` takes an absolute path, and the parent repo already has 40+
  `_gen_*.yaml` files from other experiments; adding 18 more per sweep is a
  merge hazard. Relative paths *inside* the YAML (deepspeed) are resolved against
  the CWD, so the commands `cd` into LLaMA-Factory anyway and we write the
  deepspeed path absolute for good measure.
* **`dataset_dir` points at our own registry** (`bcdata.local_dataset_info()`),
  so no adapterCL dataset has to be added to the shared
  `LLaMA-Factory/data/dataset_info.json`.
* **`output_dir` is absolute**, under `paths.OUT_CELLS`, so
  `materialize.cell_adapter_dir()` and `collect_adapters()` agree without
  copying anything out of `LLaMA-Factory/saves`.

Pure stdlib -- importable from the system python (3.6+). `collect_adapters` will
use `materialize.read_adapter` (torch/safetensors) when available and fall back
to a structural check when it is not.
"""

from __future__ import print_function

import argparse
import collections
import datetime
import json
import os
import subprocess
import sys

from . import cells, paths, targets

# --------------------------------------------------------------------------
# Recipe
# --------------------------------------------------------------------------

#: The full-SFT recipe this is derived from. Read it before changing anything
#: here -- it encodes hard-won memory settings for Qwen3.5-9B at 64k context.
BASE_RECIPE = os.path.join(paths.LLAMA_FACTORY, "examples", "train_full",
                           "_gen_tw-qwen35-9b.yaml")

#: DeepSpeed configs, absolute. ZeRO-3 *without* CPU offload is the default for
#: LoRA: offload exists in the full-SFT recipe to move 9B x (fp32 master + Adam
#: moments) off the GPU, but a LoRA's optimizer state is ~10 MB, so offload buys
#: nothing and costs a CPUAdam JIT build plus a slow optimizer step.
DS_Z3 = os.path.join(paths.LLAMA_FACTORY, "examples", "deepspeed",
                     "ds_z3_config.json")
DS_Z3_OFFLOAD = os.path.join(paths.LLAMA_FACTORY, "examples", "deepspeed",
                             "ds_z3_offload_config.json")

#: Chat template per backbone family, keyed by the substring that identifies it
#: in the model id. A WRONG TEMPLATE DOES NOT ERROR -- LLaMA-Factory happily
#: wraps the conversation in the other family's delimiters, the loss curve looks
#: ordinary, and the adapter comes out useless. So the default is not a guess:
#: `template_for` raises on a model it does not recognise, and the caller must
#: pass `template=` explicitly to override.
TEMPLATE_FOR = (
    ("qwen3.5", "qwen3_5"),
    ("qwen3_5", "qwen3_5"),
    ("llama-3.1", "llama3"),
    ("llama-3.2", "llama3"),
    ("llama-3.3", "llama3"),
)
DEFAULT_TEMPLATE = "qwen3_5"


def template_for(model):
    """LLaMA-Factory `template:` for a model id. Raises on an unknown family."""
    m = (model or "").lower()
    for needle, tpl in TEMPLATE_FOR:
        if needle in m:
            return tpl
    raise ValueError(
        "no chat template known for model %r -- add it to percell.TEMPLATE_FOR "
        "or pass template= explicitly. Guessing here would train the adapter "
        "on mis-delimited text with no error anywhere." % (model,))


DEFAULT_TAG = "percell"
DEFAULT_RANK = 16
DEFAULT_TARGET_SET = "attn_mlp"

#: Throughput assumption for the cost table. THIS IS A PLACEHOLDER: measure it in
#: Phase 1 with a single cell and pass --sec-per-step. At 64k cutoff on H200s the
#: full-SFT recipe ran on the order of tens of seconds per optimizer step; LoRA
#: removes the optimizer/communication cost but not the activations.
SEC_PER_OPTIM_STEP = 25.0

YAML_TEMPLATE = """\
### adapterCL Phase 2 -- per-cell LoRA. GENERATED by adaptercl/percell.py; do not hand-edit.
### cell        : %(cell_key)s   (env=%(env)s era=%(era)s theme=%(theme)s year=%(year)s)
### generated   : %(created)s
### derived from: %(base_recipe)s
### Every line marked DEVIATION differs from that full-SFT recipe; everything else is copied.
model_name_or_path: %(model)s
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora                     # DEVIATION: full -> lora (7 Phase 2 wants per-cell adapters)
lora_rank: %(rank)d
lora_alpha: %(alpha)g
lora_dropout: %(dropout)g
lora_target: %(lora_target)s   # DEVIATION: explicit list from targets.peft_target_modules(%(target_set)r).
                                          # NEVER `all`: it would match the vision tower and conv1d,
                                          # and vLLM drops LoRAs on non-Linear modules silently (4.5).
deepspeed: %(deepspeed)s   # DEVIATION: ZeRO-3 *without* CPU offload -- a LoRA optimizer state is tiny
flash_attn: fa2
enable_liger_kernel: true                 # as in the base recipe: fused CE keeps the 152k-vocab logits off-peak

### dataset
dataset: %(dataset)s
dataset_dir: %(dataset_dir)s   # DEVIATION: adapterCL's own registry, not LLaMA-Factory/data
template: %(template)s   # per-backbone; see TEMPLATE_FOR -- a wrong one trains on mis-delimited text and never errors
cutoff_len: %(cutoff)d                       # unchanged: TimeWarp AXTree prompts are genuinely this long
max_samples: %(max_samples)d
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: %(output_dir)s
logging_steps: %(logging_steps)d                         # DEVIATION: 10 -> %(logging_steps)d, a cell is only ~%(steps_hint)d steps
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: true                     # DEVIATION: no optimizer state; we only ever reload the adapter
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: %(grad_accum)d
learning_rate: %(lr)s                    # DEVIATION: 1.0e-5 -> %(lr)s (standard LoRA lr; the full-SFT lr underfits an adapter)
num_train_epochs: %(epochs)g                    # DEVIATION: 5 -> %(epochs)g; a cell has ~%(n_samples)d samples, so an epoch is a handful of steps
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
fp16: false
ddp_timeout: 180000000
resume_from_checkpoint: null
gradient_checkpointing: true
seed: %(seed)d
data_seed: %(seed)d
%(eval_block)s"""

EVAL_BLOCK = """
### eval
val_size: %(val_size)g
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: %(eval_steps)d
"""

#: Substituted as a *value* into YAML_TEMPLATE, so it is not %-formatted itself:
#: percent signs here must be single.
NO_EVAL_BLOCK = """
### eval -- DEVIATION: disabled. The base recipe holds out 10% of a ~4k-sample pooled
### corpus; a cell has a few hundred samples, so a 10% split is both a material loss of
### training data and too small to read. Validate by cross-applying adapters (6.2) instead.
"""


# --------------------------------------------------------------------------
# Jobs
# --------------------------------------------------------------------------

class CellJob(object):
    """One LLaMA-Factory LoRA run for one cell."""

    __slots__ = ("cell", "dataset", "dataset_dir", "target_set", "rank",
                 "alpha", "tag", "yaml_path", "output_dir", "n_samples",
                 "epochs", "grad_accum", "gpus", "n_sites", "n_params", "seed")

    def __init__(self, cell, dataset, target_set, rank, alpha, tag, yaml_path,
                 output_dir, n_samples=0, epochs=6.0, grad_accum=4, gpus=8,
                 n_sites=0, n_params=0, dataset_dir=None, seed=42):
        self.cell = cell
        self.dataset = dataset
        self.dataset_dir = dataset_dir
        self.target_set = target_set
        self.rank = rank
        self.alpha = alpha
        self.tag = tag
        self.yaml_path = yaml_path
        self.output_dir = output_dir
        self.n_samples = n_samples
        self.epochs = epochs
        self.grad_accum = grad_accum
        self.gpus = gpus
        self.n_sites = n_sites
        self.n_params = n_params
        self.seed = seed

    @property
    def name(self):
        return "%s__%s__r%d" % (self.cell.key, self.target_set, self.rank)

    def optim_steps(self):
        per_step = max(1, self.grad_accum * max(1, self.gpus))
        return int(round(self.n_samples * self.epochs / float(per_step)))

    def gpu_hours(self, sec_per_step=SEC_PER_OPTIM_STEP):
        return self.optim_steps() * sec_per_step * max(1, self.gpus) / 3600.0

    def as_dict(self):
        return {"cell": self.cell.key, "dataset": self.dataset,
                "dataset_dir": self.dataset_dir,
                "target_set": self.target_set, "rank": self.rank,
                "alpha": self.alpha, "tag": self.tag, "yaml": self.yaml_path,
                "output_dir": self.output_dir, "n_samples": self.n_samples,
                "epochs": self.epochs, "gpus": self.gpus,
                "n_sites": self.n_sites, "n_params": self.n_params,
                "optim_steps": self.optim_steps(), "seed": self.seed}

    def __repr__(self):
        return "CellJob(%s)" % self.name


def cell_output_dir(cell, tag=DEFAULT_TAG, root=None):
    """Where this cell's adapter lands. Mirrors materialize.cell_adapter_dir."""
    return os.path.join(root or paths.OUT_CELLS, tag, cell.key)


def cell_yaml_path(cell, tag=DEFAULT_TAG, root=None):
    return os.path.join(root or paths.OUT_CELLS, tag, "yaml",
                        "_gen_%s.yaml" % cell.key)


# --------------------------------------------------------------------------
# YAML generation
# --------------------------------------------------------------------------

def _env_label(unit):
    """Provenance text for the unit's environment axis.

    Unchanged for Cell ("wiki") and Version ("all"); a Site names itself and,
    for the pooled units, which sites it can draw from.
    """
    if getattr(unit, "granularity", None) == "site":
        if unit.env is not None:
            return unit.site
        return "%s(%s)" % (unit.site, ",".join(unit.sites))
    return unit.env if unit.env is not None else "all"


def _era_label(unit):
    """Provenance text for the unit's era axis: "3" for a Cell, "1-6" for a
    Site pooled over every era, "6" for an era-restricted Site, "2,4,6" for a
    non-contiguous set."""
    if unit.era is not None:
        return unit.era
    eras = getattr(unit, "eras", None)
    if not eras:
        return "all"
    eras = list(eras)
    if len(eras) == 1:
        return "%d" % eras[0]
    if eras == list(range(eras[0], eras[-1] + 1)):
        return "%d-%d" % (eras[0], eras[-1])
    return ",".join(str(e) for e in eras)


def write_cell_yaml(cell, dataset, target_set=DEFAULT_TARGET_SET,
                    rank=DEFAULT_RANK, alpha=None, out_dir=None, tag=DEFAULT_TAG,
                    model=None, epochs=6.0, lr="1.0e-4", cutoff=65536,
                    grad_accum=4, dropout=0.0, seed=42, val_size=0.0,
                    eval_steps=50, max_samples=100000, deepspeed=None,
                    dataset_dir=None, n_samples=0, yaml_path=None,
                    logging_steps=2, template=None):
    """Generate one per-cell LoRA YAML and return its path.

    `alpha` defaults to 2*rank (the PEFT convention this repo's other LoRA runs
    use); `dataset_dir` defaults to adapterCL's own registry so nothing has to be
    written into the shared LLaMA-Factory dataset_info.json.
    """
    from . import bcdata            # local: bcdata imports subprocess/shutil only

    alpha = float(2 * rank if alpha is None else alpha)
    out_dir = out_dir or cell_output_dir(cell, tag)
    yaml_path = yaml_path or cell_yaml_path(cell, tag)
    dataset_dir = dataset_dir or os.path.dirname(bcdata.local_dataset_info())
    deepspeed = deepspeed or DS_Z3
    for d in (os.path.dirname(yaml_path), out_dir):
        if not os.path.isdir(d):
            os.makedirs(d)

    modules = targets.peft_target_modules(target_set)
    body = YAML_TEMPLATE % {
        # A Version has no single env/theme -- it pools all three sites for its
        # era -- and a Site has no single era, so render those provenance fields
        # from what the unit exposes. `era` is formatted with %s, not %d, for
        # exactly that reason (a Site's era is None); for a Cell or Version the
        # rendered text is unchanged.
        "cell_key": cell.key,
        "env": _env_label(cell),
        "era": _era_label(cell),
        "theme": (cell.theme if hasattr(cell, "theme")
                  else ", ".join("%s=%s" % kv for kv in
                                 sorted(cell.themes.items()))),
        "year": cell.year,
        "created": datetime.datetime.now().isoformat(),
        "base_recipe": BASE_RECIPE,
        "model": model or paths.BASE_MODEL,
        "template": template or template_for(model or paths.BASE_MODEL),
        "rank": int(rank), "alpha": alpha, "dropout": float(dropout),
        "lora_target": ",".join(modules), "target_set": target_set,
        "deepspeed": deepspeed,
        "dataset": dataset, "dataset_dir": dataset_dir,
        "cutoff": int(cutoff), "max_samples": int(max_samples),
        "output_dir": out_dir, "logging_steps": int(logging_steps),
        "steps_hint": max(1, int(n_samples * epochs / max(1, grad_accum * 8))),
        "grad_accum": int(grad_accum), "lr": lr, "epochs": float(epochs),
        "n_samples": int(n_samples), "seed": int(seed),
        "eval_block": (EVAL_BLOCK % {"val_size": val_size,
                                     "eval_steps": int(eval_steps)}
                       if val_size and val_size > 0 else NO_EVAL_BLOCK),
    }
    with open(yaml_path, "w") as fh:
        fh.write(body)
    return yaml_path


def make_jobs(cell_list=None, target_sets=(DEFAULT_TARGET_SET,),
              ranks=(DEFAULT_RANK,), tag=DEFAULT_TAG, manifest=None,
              gpus=8, epochs=6.0, grad_accum=4, write_yaml=True, seed=42,
              cfg=None, **yaml_kw):
    """Build the job list (and, by default, the YAMLs) for a sweep.

    `manifest` is the dict written by `bcdata.build_cell_corpora`; without it we
    fall back to the census for sample counts and to the conventional dataset
    name `adaptercl_<tag>_<cell>`, so the plan can be costed before any corpus
    exists.
    """
    from . import bcdata

    cell_list = list(cell_list or cells.ALL_CELLS)
    if cfg is None:
        try:
            cfg = targets.load_text_config()
        except (IOError, KeyError) as exc:
            print("NOTE: could not read the model config (%s); parameter counts "
                  "in the plan will be 0." % exc)
            cfg = None

    counts, datasets = {}, {}
    if manifest:
        for key, rec in manifest.get("cells", {}).items():
            counts[key] = rec.get("n_samples", 0)
            datasets[key] = rec.get("dataset")
    else:
        cen = bcdata.census()
        for key, rec in cen["per_cell"].items():
            counts[key] = rec["verified_steps"]

    jobs, skipped = [], []
    for c in cell_list:
        n = counts.get(c.key, 0)
        if n <= 0:
            skipped.append(c.key)
            continue
        ds = datasets.get(c.key) or "adaptercl_%s_%s" % (tag, c.key)
        for ts in target_sets:
            for r in ranks:
                sites = targets.enumerate_sites(cfg, ts) if cfg else []
                sub_tag = tag if (len(target_sets) == 1 and len(ranks) == 1) \
                    else "%s_%s_r%d" % (tag, ts, r)
                out_dir = cell_output_dir(c, sub_tag)
                ypath = cell_yaml_path(c, sub_tag)
                job = CellJob(c, ds, ts, r, 2 * r, sub_tag, ypath, out_dir,
                              n_samples=n, epochs=epochs, grad_accum=grad_accum,
                              gpus=gpus, n_sites=len(sites),
                              n_params=targets.site_budget(sites, r) if sites else 0,
                              seed=seed)
                if write_yaml:
                    write_cell_yaml(c, ds, target_set=ts, rank=r, tag=sub_tag,
                                    out_dir=out_dir, yaml_path=ypath,
                                    epochs=epochs, grad_accum=grad_accum,
                                    n_samples=n, seed=seed, **yaml_kw)
                jobs.append(job)
    if skipped:
        print("SKIPPED %d cell(s) with no BC data: %s"
              % (len(skipped), ", ".join(skipped)))
        print("  (that is adapterCL.md 7 Phase 2's 18-cell design failing on "
              "the data that exists -- see `python -m adaptercl.bcdata census`)")
    return jobs


# --------------------------------------------------------------------------
# Planning / costing
# --------------------------------------------------------------------------

def plan_sweep(cell_list=None, target_sets=(DEFAULT_TARGET_SET,),
               ranks=(DEFAULT_RANK,), tag=DEFAULT_TAG, gpus=8, epochs=6.0,
               grad_accum=4, sec_per_step=SEC_PER_OPTIM_STEP, manifest=None,
               write_yaml=False, fh=None):
    """The Phase-1/Phase-2 job list with an estimated cost, printed as a table.

    Phase 1 (4.5's injection-site sweep) is this with one cell and many
    (target_set, rank) pairs; Phase 2 is this with all cells and one pair.
    """
    fh = fh or sys.stdout
    jobs = make_jobs(cell_list, target_sets, ranks, tag=tag, gpus=gpus,
                     epochs=epochs, grad_accum=grad_accum, manifest=manifest,
                     write_yaml=write_yaml)
    print("sweep plan: %d job(s)  |  %d cell(s) x %d target set(s) x %d rank(s)"
          % (len(jobs), len(set(j.cell.key for j in jobs)), len(target_sets),
             len(ranks)), file=fh)
    print("  gpus/job=%d  epochs=%g  grad_accum=%d  sec/optim-step=%g (ASSUMPTION)"
          % (gpus, epochs, grad_accum, sec_per_step), file=fh)
    print("", file=fh)
    hdr = ("  %-10s %-14s %5s %7s %12s %8s %10s %9s"
           % ("cell", "targets", "rank", "sites", "lora params", "samples",
              "opt steps", "gpu-hrs"))
    print(hdr, file=fh)
    print("  " + "-" * (len(hdr) - 2), file=fh)
    total_h, total_steps = 0.0, 0
    for j in jobs:
        h = j.gpu_hours(sec_per_step)
        total_h += h
        total_steps += j.optim_steps()
        print("  %-10s %-14s %5d %7d %12s %8d %10d %9.1f"
              % (j.cell.key, j.target_set, j.rank, j.n_sites,
                 "{:,}".format(j.n_params), j.n_samples, j.optim_steps(), h),
              file=fh)
    print("  " + "-" * (len(hdr) - 2), file=fh)
    print("  %-10s %-14s %5s %7s %12s %8s %10d %9.1f"
          % ("TOTAL", "", "", "", "", "", total_steps, total_h), file=fh)
    print("", file=fh)
    print("  ~%.1f GPU-hours (~%.1f wall-hours on %d GPUs, serial)."
          % (total_h, total_h / max(1, gpus), gpus), file=fh)
    thin = [j for j in jobs if j.optim_steps() < 50]
    if thin:
        print("", file=fh)
        print("  WARNING: %d job(s) get fewer than 50 optimizer steps "
              "(min %d, cell %s)."
              % (len(thin), min(j.optim_steps() for j in thin),
                 min(jobs, key=lambda j: j.optim_steps()).cell.key), file=fh)
        print("  A cell has only a few hundred samples and the effective batch "
              "here is %d (grad_accum %d x %d GPUs),"
              % (grad_accum * gpus, grad_accum, gpus), file=fh)
        print("  so a per-cell LoRA sees almost no updates. Fix by lowering "
              "--grad-accum (to 1) and/or raising", file=fh)
        print("  --epochs; the Phase-1 kill criterion ('no injection-site "
              "configuration lets plain LoRA improve a", file=fh)
        print("  single version') is only meaningful once the optimizer has "
              "actually run.", file=fh)
    print("  The 6.2 transfer matrix on top of this is |cells|^2 evaluations, "
          "not trainings.", file=fh)
    return jobs


# --------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------

def env_preamble(extra=None):
    """The spack toolchain LLaMA-Factory training needs.

    Without `SPACK_GCC_BIN` on PATH and `CUDA_HOME` pointing at the cu130
    toolkit, DeepSpeed's CPUAdam JIT build fails (torch here is a cu130 build and
    the system CUDA is 12.5) and tilelang's Qwen3.5 FLA kernels will not compile
    under system g++ 8.5. Copied from LLaMA-Factory/run.sh and
    self-correct/sft_cell.sh, but using paths.SPACK_* (the *current* spack tree --
    sft_cell.sh still names the v10 tree, which has moved).
    """
    lines = []
    if paths.SPACK_GCC_BIN:
        lines.append('export PATH="%s:$PATH"' % paths.SPACK_GCC_BIN)
    if paths.SPACK_CUDA_HOME:
        lines.extend(('export CUDA_HOME="%s"' % paths.SPACK_CUDA_HOME,
                      'export PATH="$CUDA_HOME/bin:$PATH"'))
    lines.extend(('export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True',
                  'export FORCE_TORCHRUN=1',
                  'export DISABLE_VERSION_CHECK=1'))
    lines.extend(extra or [])
    return lines


def build_commands(jobs, gpus=None, cuda_visible_devices=None, log_dir=None):
    """Exact shell commands to train each job, preamble included.

    Returns [{"job", "cmd", "log"}]. `cmd` is a single `bash -c`-safe string:
    LLaMA-Factory resolves relative paths against the CWD, so it cds into the
    LLaMA-Factory root even though our YAML/output paths are absolute.
    """
    log_dir = log_dir or os.path.join(paths.OUT_LOGS, "percell")
    out = []
    for j in jobs:
        pre = list(env_preamble())
        if cuda_visible_devices:
            pre.append('export CUDA_VISIBLE_DEVICES=%s' % cuda_visible_devices)
        if gpus:
            pre.append('export NPROC_PER_NODE=%d' % gpus)
        log = os.path.join(log_dir, "%s.log" % j.name)
        cmd = "; ".join(pre + ['cd "%s"' % paths.LLAMA_FACTORY,
                               '"%s" train "%s"' % (paths.LMF, j.yaml_path)])
        out.append({"job": j, "cmd": cmd, "log": log})
    return out


def write_launcher(jobs, path=None, gpus=None, cuda_visible_devices=None,
                   log_dir=None):
    """Write a runnable bash script for the whole sweep (still not launched)."""
    path = path or os.path.join(paths.OUT_CELLS, "run_percell.sh")
    d = os.path.dirname(path)
    if d and not os.path.isdir(d):
        os.makedirs(d)
    log_dir = log_dir or os.path.join(paths.OUT_LOGS, "percell")
    if not os.path.isdir(log_dir):
        os.makedirs(log_dir)
    cmds = build_commands(jobs, gpus=gpus,
                          cuda_visible_devices=cuda_visible_devices,
                          log_dir=log_dir)
    lines = ["#!/usr/bin/env bash",
             "# GENERATED by adaptercl/percell.py on %s"
             % datetime.datetime.now().isoformat(),
             "# Run this inside a tmux window on an allocation, never on the "
             "login node.",
             "set -uo pipefail", ""]
    for rec in cmds:
        j = rec["job"]
        lines.append('echo "==== %s (%d samples, %d optim steps) ===="'
                     % (j.name, j.n_samples, j.optim_steps()))
        lines.append("( %s ) 2>&1 | tee %s" % (rec["cmd"], rec["log"]))
        lines.append("")
    with open(path, "w") as fh:
        fh.write("\n".join(lines))
    os.chmod(path, 0o755)
    return path


def run(jobs, execute=False, gpus=None, cuda_visible_devices=None,
        log_dir=None):
    """Dry-run by default. Refuses to launch without `execute=True`.

    Even with `execute=True` it checks for a visible GPU first: launching a 9B
    LoRA on a login node is the failure mode this guard exists for.
    """
    cmds = build_commands(jobs, gpus=gpus,
                          cuda_visible_devices=cuda_visible_devices,
                          log_dir=log_dir)
    if not execute:
        print("DRY RUN -- %d job(s). Nothing launched. Pass execute=True "
              "(CLI: --execute) to run, and do it inside tmux on an "
              "allocation." % len(cmds))
        for rec in cmds:
            print("")
            print("# %s -> %s" % (rec["job"].name, rec["job"].output_dir))
            print(rec["cmd"])
        return {"executed": False, "commands": [c["cmd"] for c in cmds]}

    try:
        subprocess.check_output(["nvidia-smi", "-L"])
    except (OSError, subprocess.CalledProcessError):
        raise RuntimeError(
            "no GPU visible (nvidia-smi -L failed). Refusing to launch %d "
            "LLaMA-Factory job(s). Allocate a node first." % len(cmds))
    results = []
    for rec in cmds:
        d = os.path.dirname(rec["log"])
        if not os.path.isdir(d):
            os.makedirs(d)
        print("==== %s ====" % rec["job"].name)
        with open(rec["log"], "w") as fh:
            rc = subprocess.call(["bash", "-c", rec["cmd"]], stdout=fh,
                                 stderr=subprocess.STDOUT)
        print("  rc=%d  log=%s" % (rc, rec["log"]))
        results.append({"job": rec["job"].name, "rc": rc, "log": rec["log"]})
    return {"executed": True, "results": results}


# --------------------------------------------------------------------------
# Collection
# --------------------------------------------------------------------------

def _structural_check(adapter_dir):
    """Adapter sanity without torch: config parses and a weight file exists."""
    cfg_path = os.path.join(adapter_dir, "adapter_config.json")
    if not os.path.exists(cfg_path):
        return None, "no adapter_config.json"
    try:
        with open(cfg_path) as fh:
            cfg = json.load(fh)
    except ValueError as exc:
        return None, "unreadable adapter_config.json: %s" % exc
    for name in ("adapter_model.safetensors", "adapter_model.bin"):
        if os.path.exists(os.path.join(adapter_dir, name)):
            return cfg, None
    return cfg, "no adapter weights"


def collect_adapters(tag=DEFAULT_TAG, cell_list=None, root=None, validate=True,
                     quiet=False):
    """Map cell -> adapter dir for a finished sweep, validating each one.

    LLaMA-Factory writes the adapter at the top of `output_dir` and a copy per
    epoch under `checkpoint-*`; we prefer the top-level one and fall back to the
    highest-numbered checkpoint (which is what you get if the run was killed
    after an epoch but before `save_model`).
    """
    cell_list = list(cell_list or cells.ALL_CELLS)
    found, missing, bad = collections.OrderedDict(), [], collections.OrderedDict()
    reader = None
    if validate:
        try:
            from . import materialize
            reader = materialize.read_adapter
        except ImportError as exc:      # torch/safetensors absent (py3.6)
            if not quiet:
                print("NOTE: materialize.read_adapter unavailable (%s); "
                      "falling back to a structural check." % exc)

    for c in cell_list:
        d = cell_output_dir(c, tag, root=root)
        cand = d
        if not os.path.exists(os.path.join(d, "adapter_config.json")):
            ckpts = []
            if os.path.isdir(d):
                for name in os.listdir(d):
                    if name.startswith("checkpoint-") and name[11:].isdigit():
                        ckpts.append((int(name[11:]), os.path.join(d, name)))
            cand = sorted(ckpts)[-1][1] if ckpts else None
        if cand is None:
            missing.append(c.key)
            continue
        cfg, err = _structural_check(cand)
        if err:
            bad[c.key] = "%s (%s)" % (err, cand)
            continue
        rec = {"dir": cand, "r": cfg.get("r"),
               "lora_alpha": cfg.get("lora_alpha"),
               "target_modules": cfg.get("target_modules")}
        if reader is not None:
            try:
                factors, cfg2, meta = reader(cand)
                rec["n_sites"] = len(factors)
                rec["n_params"] = sum(int(A.numel()) + int(B.numel())
                                      for A, B in factors.values())
                rec["validated"] = "read_adapter"
            except ImportError as exc:
                # materialize imports torch/safetensors lazily *inside* its
                # functions, so the import above succeeds under python 3.6 and
                # only the call fails. That is an environment limitation, not a
                # bad adapter -- degrade to the structural check.
                if not quiet:
                    print("NOTE: read_adapter needs %s; falling back to a "
                          "structural check (run under %s for the full check)."
                          % (exc, paths.PY_TRAIN))
                reader = None
                rec["validated"] = "structural"
            except Exception as exc:               # noqa: BLE001 - report, don't hide
                bad[c.key] = "read_adapter failed: %s (%s)" % (exc, cand)
                continue
        else:
            rec["validated"] = "structural"
        found[c.key] = rec

    if not quiet:
        print("adapters for tag %r under %s" % (tag, root or paths.OUT_CELLS))
        for key, rec in found.items():
            print("  %-10s r=%-3s sites=%-4s params=%-12s %s"
                  % (key, rec.get("r"), rec.get("n_sites", "-"),
                     "{:,}".format(rec["n_params"]) if "n_params" in rec else "-",
                     rec["dir"]))
        if bad:
            for key, why in bad.items():
                print("  %-10s INVALID: %s" % (key, why))
        if missing:
            print("  missing (%d): %s" % (len(missing), ", ".join(missing)))
        print("  %d/%d cells present" % (len(found), len(cell_list)))
    return {"tag": tag, "found": found, "missing": missing, "invalid": bad}


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def _cells_arg(spec):
    from .bcdata import _cells_arg as f
    return f(spec)


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Phase-2 per-cell LoRA jobs (adapterCL.md 7)")
    sub = ap.add_subparsers(dest="cmd")

    def common(p):
        p.add_argument("--cells", default="all")
        p.add_argument("--tag", default=DEFAULT_TAG)
        p.add_argument("--targets", default=DEFAULT_TARGET_SET,
                       help="comma list of target-set names (%s)"
                            % ",".join(targets.TARGET_SETS))
        p.add_argument("--ranks", default=str(DEFAULT_RANK))
        p.add_argument("--gpus", type=int, default=8)
        p.add_argument("--epochs", type=float, default=6.0)
        p.add_argument("--grad-accum", type=int, default=4)
        p.add_argument("--manifest", default=None,
                       help="bcdata.build_cell_corpora manifest.json")
        return p

    p = common(sub.add_parser("sweep", help="print the job plan + cost"))
    p.add_argument("--sec-per-step", type=float, default=SEC_PER_OPTIM_STEP)
    p.add_argument("--write-yaml", action="store_true")

    p = common(sub.add_parser("yaml", help="generate the per-cell YAMLs"))

    p = common(sub.add_parser("commands", help="print the training commands"))
    p.add_argument("--launcher", nargs="?", const="", default=None,
                   help="also write a launcher script (optional path)")

    p = common(sub.add_parser("run", help="dry-run by default"))
    p.add_argument("--execute", action="store_true",
                   help="actually launch (needs a GPU; use tmux on an "
                        "allocation)")

    p = sub.add_parser("collect", help="collect + validate trained adapters")
    p.add_argument("--cells", default="all")
    p.add_argument("--tag", default=DEFAULT_TAG)
    p.add_argument("--no-validate", action="store_true")

    args = ap.parse_args(argv)
    cmd = args.cmd or "sweep"

    if cmd == "collect":
        collect_adapters(args.tag, _cells_arg(args.cells),
                         validate=not args.no_validate)
        return 0

    manifest = None
    if getattr(args, "manifest", None):
        with open(args.manifest) as fh:
            manifest = json.load(fh)
    tsets = tuple(t.strip() for t in args.targets.split(",") if t.strip())
    ranks = tuple(int(r) for r in args.ranks.split(",") if r.strip())
    cell_list = _cells_arg(args.cells)

    if cmd == "sweep":
        plan_sweep(cell_list, tsets, ranks, tag=args.tag, gpus=args.gpus,
                   epochs=args.epochs, grad_accum=args.grad_accum,
                   sec_per_step=args.sec_per_step, manifest=manifest,
                   write_yaml=args.write_yaml)
        return 0

    jobs = make_jobs(cell_list, tsets, ranks, tag=args.tag, gpus=args.gpus,
                     epochs=args.epochs, grad_accum=args.grad_accum,
                     manifest=manifest, write_yaml=(cmd != "run") or True)
    if cmd == "yaml":
        for j in jobs:
            print("%-24s %s" % (j.name, j.yaml_path))
        return 0
    if cmd == "commands":
        for rec in build_commands(jobs, gpus=args.gpus):
            print("")
            print("# %s" % rec["job"].name)
            print(rec["cmd"])
        if args.launcher is not None:
            path = write_launcher(jobs, args.launcher or None, gpus=args.gpus)
            print("\nlauncher: %s" % path)
        return 0
    if cmd == "run":
        run(jobs, execute=args.execute, gpus=args.gpus)
        return 0

    ap.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
